version: '3.9'

services:
  #  Kafka
  zookeeper:
    image: wurstmeister/zookeeper
    expose:
      - 2181
  kafka:
    image: wurstmeister/kafka
    expose:
      - 9092
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "conveyor-finish-registration:1:1,conveyor-create-documents:1:1,conveyor-send-documents:1:1,conveyor-send-ses:1:1,conveyor-credit-issued:1:1,conveyor-application-denied:1:1"
  prometheus:
    image: prom/prometheus
    ports:
      - '9090:9090'
    container_name: prometheus
    volumes:
      - ./deal/src/main/resources/prometheus.yaml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus
  grafana:
    image: grafana/grafana
    container_name: 'grafana'
    ports:
      - '3000:3000'
    depends_on:
      - prometheus