spring:
  main:
    allow-circular-references: true
custom:
  feign:
    url:
      application: 'http://localhost:8081/application'
      deal: 'http://localhost:8082/deal'
      audit: 'http://localhost:8084/audit'
  swagger:
    service:
      url: 'http://localhost:8880'
logging:
  level:
    org:
      zalando:
        logbook: TRACE
