name: Qodana
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Qodana Scan credit-conveyor'
        working-directory: ./credit-conveyor
        uses: JetBrains/qodana-action@v2022.3.0
#      - uses: github/codeql-action/upload-sarif@v2
#        with:
#          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json