name: Qodana
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  qodana:
    runs-on: ubuntu-latest
#    defaults:
#      uses:
#        working-directory: ./conveyor
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          echo "A initial message"
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          brew install jetbrains/utils/qodana
          cd ./conveyor
          qodana init
          qodana scan --show-report
          ls -a
          echo "finish mess"
#          qodana scan --show-report
#      - name: 'Qodana Scan conveyor'
#        uses: JetBrains/qodana-action@v2022.3.0
#        with:
#          entrypoint: cd ./conveyor
#      - name: 'ls -a'
#        run: |
#          echo "A initial message"
#          ls -a
#          cd ./conveyor
#          ls -a
#          echo "finish mess"
#        working-directory: ./conveyor
#        run: realpath OfferService.java
#      - uses: github/codeql-action/upload-sarif@v2
#        with:
#          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json